#
# This source file is part of the StrokeCog based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
    permissions:
      contents: read
  markdownlinkcheck:
    name: Markdown Link Check
    uses: StanfordBDHG/.github/.github/workflows/markdown-link-check.yml@v2
    permissions:
      contents: read
  build:
    name: Build
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Check Environment
      run: |
          xcodebuild -version
          swift --version
    - name: Set Mapbox Credentials
      run: |
        echo "machine api.mapbox.com" >> ~/.netrc
        echo "login mapbox" >> ~/.netrc
        echo "password ${{ secrets.MAPBOX_TOKEN }}" >> ~/.netrc
        chmod 0600 ~/.netrc
    - name: Build
      run: xcodebuild test -project StrokeCog.xcodeproj -scheme StrokeCog -destination 'platform=iOS Simulator,name=iPhone 15 Pro'
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: buildandtest
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    permissions:
      contents: read
    with:
      coveragereports: StrokeCog.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
