#
# This source file is part of LifeSpace based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
    permissions:
      contents: read
  markdownlinkcheck:
    name: Markdown Link Check
    uses: StanfordBDHG/.github/.github/workflows/markdown-link-check.yml@v2
    permissions:
      contents: read
  buildandtest:
    name: Build and Test
    runs-on: [self-hosted, macos-14]
    steps:
      - uses: actions/checkout@v4
      - name: Add Mapbox credentials
        uses: extractions/netrc@v1
        with:
          machine: api.mapbox.com
          username: mapbox
          password: ${{ secrets.MAPBOX_TOKEN }}
      - name: Write Mapbox credentials to file for Xcode build
        run: echo "${{ secrets.MAPBOX_TOKEN }}" > .mapbox
      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.3'
      - name: Build Xcode project
        run: xcodebuild -project LifeSpace.xcodeproj -scheme LifeSpace -sdk iphonesimulator -configuration Debug build
      - name: Run tests
        run: xcodebuild test -project LifeSpace.xcodeproj -scheme LifeSpace -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=17.2'