#
# This source file is part of the StrokeCog based on the Stanford Spezi Template Application project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  swiftlint:
    name: SwiftLint
    uses: StanfordBDHG/.github/.github/workflows/swiftlint.yml@v2
    permissions:
      contents: read
  markdownlinkcheck:
    name: Markdown Link Check
    uses: StanfordBDHG/.github/.github/workflows/markdown-link-check.yml@v2
    permissions:
      contents: read